manifest_version = 1

[module]
id = "fts"
name = "First Time Sync!"
description = "First Time Sync. Used in https://github.com/alf1e/my-one-click-apps"
version = "1.0.0"
license = "MIT"
authors = ["ItsMeAlfie0"]
